### ISSUE TITLE
Incorrect indefinite articles post-Shaqtivation

### ISSUE THREAD

**Issue by jdreic** [benstone1/Shaqtivator#1]
"An" is not corrected to "A" post-Shaqtivation of following word. See:

<img width="704" alt="screen shot 2018-09-14 at 11 15 13 am" src="https://user-images.githubusercontent.com/27450018/45559065-79a9ee00-b80f-11e8-9675-0363cba746b1.png">

**Comment by benstone1** [comment]
Nice catch, lots of edge cases with these.  Fixed in 1.11 with https://github.com/benstone1/Shaqtivator/commit/8828285e723cca3ac1dd0172d94473dd4830ec79

**Comment by benstone1** [comment]
https://individualengineer.wordpress.com/2012/05/27/what-it-means-to-have-an-active-mind/ should be a test for it
